-- 911 Analytics — schema initial
-- À exécuter une seule fois dans l'éditeur SQL de ton projet Supabase
-- (Dashboard > SQL Editor > New query > coller > Run)

create table if not exists public.listings (
  id text primary key,
  model text not null,
  generation text not null,
  phase text not null,
  image text not null,
  price integer not null,
  mileage integer not null,
  year integer not null,
  power integer not null,
  fuel_type text not null,
  transmission text not null,
  country text not null,
  country_flag text not null,
  city text not null,
  seller text not null,
  seller_type text not null,
  seller_rating numeric not null,
  seller_phone text not null,
  seller_email text not null,
  listing_url text not null,
  listing_source text not null,
  conformity integer not null,
  published_days_ago integer not null,
  options jsonb not null default '[]'::jsonb,
  vigilance_points jsonb not null default '[]'::jsonb,
  negotiation_arguments jsonb not null default '[]'::jsonb,
  price_history jsonb not null default '[]'::jsonb,
  value_analysis jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.listings enable row level security;

-- Tout le monde peut lire les annonces (c'est un moteur de recherche public).
-- Aucune policy d'insert/update/delete n'est créée : par défaut, RLS refuse
-- ces opérations pour la clé "anon" utilisée par le frontend.
create policy "Public read access on listings"
  on public.listings for select
  using (true);
insert into public.listings (
  id, model, generation, phase, image,
  price, mileage, year, power, fuel_type, transmission,
  country, country_flag, city, seller, seller_type,
  seller_rating, seller_phone, seller_email, listing_url, listing_source,
  conformity, published_days_ago, options, vigilance_points,
  negotiation_arguments, price_history, value_analysis
) values
  ('1', '911 Carrera S', '997', 'Phase I', 'https://images.pexels.com/photos/36626909/pexels-photo-36626909.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 42500, 82000, 2005, 355, 'Essence', 'Manuelle', 'France', 'FR', 'Lyon', 'Auto Lyon Premium', 'Professionnel', 4.2, '+33 4 78 00 00 01', 'contact@autolyonpremium.fr', 'https://www.leboncoin.fr/voiture/911-carrera-s-997-1', 'LeBonCoin', 72, 2, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":false},{"key":"sportChrono","label":"Pack Sport Chrono","present":false},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"critical","title":"Alerte Cylindres Rayés","description":"Moteur 3.8 Phase I — risque connu de rayures de cylindre. Test Piwi impératif + contrôle compression."},{"severity":"warning","title":"Embrayage non documenté","description":"Aucune facture de remplacement mentionnée. Budget prévisionnel ~1 200 € à prévoir."},{"severity":"info","title":"IMS non confirmé","description":"Roulement IMS original potentiellement non remplacé. Demander preuve ou prévoir remplacement."}]'::jsonb, '["Absence du kit X51 et sièges sport — options représentant ~4 500 € à neuf, manquantes sur ce modèle.","Kilométrage supérieur à 80 000 km sans preuve de vidange boîte PDK récente — risque de surcoût immédiat.","Aucune facture d''embrayage — argument fort pour obtenir une remise de 1 500 à 2 000 €."]'::jsonb, '[{"year":2005,"price":95000},{"year":2007,"price":72000},{"year":2009,"price":55000},{"year":2011,"price":42000},{"year":2013,"price":36000},{"year":2015,"price":33000},{"year":2017,"price":32000},{"year":2019,"price":34000},{"year":2021,"price":38000},{"year":2023,"price":41000},{"year":2025,"price":43000},{"year":2026,"price":42500}]'::jsonb, '{"retentionScore":6.5,"rarityLabel":"Modérée","trend":"stable","trendLabel":"Stabilité garantie","factors":["Phase I moins recherchée que la Phase II (évolutions moteur et DFI)","Problème connu des cylindres rayés qui pèse sur la cote","Kits X51 et options sportives très recherchés si présents","Commence à attirer les collectionneurs du « dernier flat-6 atmosphérique »"]}'::jsonb),
  ('2', '911 Carrera S', '997', 'Phase II', 'https://images.pexels.com/photos/31636698/pexels-photo-31636698.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 58900, 51000, 2009, 385, 'Essence', 'Automatique / PDK', 'France', 'FR', 'Bordeaux', 'Particulier', 'Particulier', 4.5, '+33 5 56 00 00 02', 'particulier.bordeaux@example.fr', 'https://www.lacentrale.fr/annonce-911-997-2', 'La Centrale', 85, 1, '[{"key":"x51","label":"X51 Powerkit","present":true},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"warning","title":"Distribution à vérifier","description":"Courroie accessoire à 60 000 km non facturée. Contrôle visuel recommandé."},{"severity":"info","title":"Coque PCM 3.0","description":"Mise à jour firmware PCM conseillée pour compatibilité Bluetooth récente."},{"severity":"info","title":"Pneus arrière","description":"Usure estimée à 40 % restant. Négociable sur le prix ou remplacement à demander."}]'::jsonb, '["Pneus arrière à 40 % d''usure restant — demande de remplacement ou remise de 600 € justifiée.","Courroie accessoire non facturée à 60 000 km — intervention à programmer, ~350 € à négocier.","Prix affiché 5 % au-dessus de la cote Argus pour cette configuration — marge de négociation de 2 500 à 3 000 €."]'::jsonb, '[{"year":2009,"price":105000},{"year":2011,"price":82000},{"year":2013,"price":62000},{"year":2015,"price":50000},{"year":2017,"price":45000},{"year":2019,"price":47000},{"year":2021,"price":52000},{"year":2023,"price":56000},{"year":2025,"price":59500},{"year":2026,"price":58900}]'::jsonb, '{"retentionScore":8.5,"rarityLabel":"Élevée","trend":"up","trendLabel":"Plus-value attendue","factors":["Fiabilité moteur grandement améliorée (DFI, plus de cylindres rayés)","Boîte PDK Gen 2 réputée pour sa robustesse","Dernière 997 à moteur atmosphérique avant le turbo de la 991","Cote en hausse continue depuis 2020, demande supérieure à l''offre"]}'::jsonb),
  ('3', '911 Carrera 4S', '991', 'Phase I', 'https://images.pexels.com/photos/30968112/pexels-photo-30968112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 78000, 38000, 2013, 400, 'Essence', 'Automatique / PDK', 'Allemagne', 'DE', 'Stuttgart', 'Porsche Center Stuttgart', 'Professionnel', 4.8, '+49 711 000 0003', 'verkauf@porsche-stuttgart.de', 'https://www.mobile.de/fahrzeuge/911-4s-991-1', 'mobile.de', 91, 0, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":true}]'::jsonb, '[{"severity":"info","title":"Première révision des 40 000 km","description":"Approche de la révision majeure. Vérifier que le carnet est à jour."},{"severity":"info","title":"PCM 3.1","description":"Système de navigation potentiellement non mis à jour. Mise à jour possible chez Porsche."}]'::jsonb, '["Révision des 40 000 km imminente — coût estimé 800 à 1 200 €, argument de négociation.","Prix légèrement supérieur au marché allemand pour ce kilométrage — marge de 2 000 à 3 500 €.","Absence du kit X51 sur une 4S — option rare et recherchée, manque de valeur à souligner."]'::jsonb, '[{"year":2013,"price":120000},{"year":2015,"price":85000},{"year":2017,"price":70000},{"year":2019,"price":62000},{"year":2021,"price":68000},{"year":2023,"price":74000},{"year":2025,"price":79000},{"year":2026,"price":78000}]'::jsonb, '{"retentionScore":7.5,"rarityLabel":"Modérée","trend":"stable","trendLabel":"Stabilité garantie","factors":["991 Phase I — première génération à élargissement d''empattement, controversée mais aboutie","Moteur 3.4 atmosphérique, dernier Carrera sans turbo (hors GT3)","Cote stable, légère hausse depuis 2022","4S avec transmission intégrale, recherchée dans les régions montagneuses"]}'::jsonb),
  ('4', '911 GT3', '991', 'GT3', 'https://images.pexels.com/photos/37985719/pexels-photo-37985719.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 145000, 18000, 2016, 475, 'Essence', 'Automatique / PDK', 'Allemagne', 'DE', 'Munich', 'GT Motors Munich', 'Professionnel', 4.9, '+49 89 000 0004', 'info@gtmotors-munich.de', 'https://www.mobile.de/fahrzeuge/911-gt3-991', 'mobile.de', 95, 3, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":true}]'::jsonb, '[{"severity":"warning","title":"Historique piste à vérifier","description":"GT3 potentiellement utilisée en track days. Demander le data logger et l''historique des tours."},{"severity":"info","title":"Rodage moteur","description":"Vérifier que le rodage des 3 000 km a été respecté (indicateur dans le PCM)."}]'::jsonb, '["Historique piste non documenté — risque de surusure moteur, argument pour 5 000 à 8 000 € de remise.","Pneus sport semi-slicks à vérifier — remplacement à ~2 000 € si usés.","Garantie Porsche Extended Performance expirée — négocier une extension ou une remise équivalente."]'::jsonb, '[{"year":2016,"price":180000},{"year":2018,"price":150000},{"year":2020,"price":135000},{"year":2022,"price":155000},{"year":2024,"price":148000},{"year":2026,"price":145000}]'::jsonb, '{"retentionScore":9.5,"rarityLabel":"Très élevée","trend":"up","trendLabel":"Plus-value attendue","factors":["GT3 991.1 — dernier GT3 à moteur atmosphérique 3.8 (475 ch)","Version PDK ultra recherchée pour la conduite sur piste","Production limitée, demande très supérieure à l''offre","Cote en forte hausse depuis 2021, phénomène de collection confirmé"]}'::jsonb),
  ('5', '911 Carrera', '993', 'Carrera', 'https://images.pexels.com/photos/38234790/pexels-photo-38234790.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 89000, 65000, 1996, 272, 'Essence', 'Manuelle', 'Italie', 'IT', 'Milano', 'Classic Auto Milano', 'Professionnel', 4.6, '+39 02 000 0005', 'info@classicautomilano.it', 'https://www.autoscout24.it/911-993-carrera', 'AutoScout24', 88, 5, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":false},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":false},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"critical","title":"Trappe de fusée avant","description":"Point de corrosion connu sur la 993. Inspection impérative du longeron avant."},{"severity":"warning","title":"Chauffage pneumatique","description":"Système de chauffage pneumatique à air souvent défaillant. Remplacement par kit électrique fréquent."},{"severity":"info","title":"Joint de culasse","description":"Remplacement du joint de culasse recommandé si jamais fait. Budget ~1 500 €."}]'::jsonb, '["Corrosion longeron avant à expertiser — si présente, remise de 3 000 à 5 000 € justifiée.","Système de chauffage pneumatique probablement à remplacer — budget ~800 €.","Kilométrage de 65 000 km non certifié (compteur analogique) — demander les factures originales."]'::jsonb, '[{"year":1996,"price":70000},{"year":2000,"price":45000},{"year":2005,"price":35000},{"year":2010,"price":30000},{"year":2015,"price":42000},{"year":2018,"price":55000},{"year":2020,"price":68000},{"year":2022,"price":78000},{"year":2024,"price":86000},{"year":2026,"price":89000}]'::jsonb, '{"retentionScore":9.8,"rarityLabel":"Très élevée","trend":"up","trendLabel":"Plus-value attendue","factors":["Dernière génération à refroidissement par air — statut culte absolu","Cote en hausse continue et soutenue depuis 2015","Modèle de collection confirmé, demande mondiale supérieure à l''offre","Boîte manuelle 6 vitesses recherchée par les puristes"]}'::jsonb),
  ('6', '911 Carrera S', '992', 'Carrera S', 'https://images.pexels.com/photos/28984433/pexels-photo-28984433.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 132000, 12000, 2022, 450, 'Essence', 'Automatique / PDK', 'Belgique', 'BE', 'Bruxelles', 'Porsche Brussels', 'Professionnel', 4.7, '+32 2 000 0006', 'sales@porsche-brussels.be', 'https://www.autoscout24.be/911-992-carrera-s', 'AutoScout24', 93, 1, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":true}]'::jsonb, '[{"severity":"info","title":"Garantie constructeur","description":"Véhicule encore sous garantie Porsche jusqu''en 2024. Vérifier le transfert."},{"severity":"info","title":"Mises à jour logicielles","description":"Vérifier que toutes les campagnes de rappel et mises à jour PCM ont été effectuées."}]'::jsonb, '["Véhicule récent sous garantie — peu de marge, mais options non incluses à négocier (entretien offert, kit hiver).","Prix au-dessus du neuf configuré équivalent — comparer avec commande directe chez Porsche.","Pneus d''origine potentiellement à remplacer prochainement (usure prématurée connue sur 992)."]'::jsonb, '[{"year":2022,"price":145000},{"year":2023,"price":138000},{"year":2024,"price":134000},{"year":2025,"price":132000},{"year":2026,"price":132000}]'::jsonb, '{"retentionScore":7,"rarityLabel":"Faible","trend":"down","trendLabel":"Décote résiduelle","factors":["992 encore en production — décote normale en cours","Motorisation turbo 3.0 décriée par les puristes, impact modéré sur la cote","Marché saturé de 992 d''occasion récentes, pression sur les prix","Rétention attendue à long terme incertaine, dépend de l''évolution du marché électrique"]}'::jsonb),
  ('7', '911 Carrera 4', '996', 'Phase II', 'https://images.pexels.com/photos/2475808/pexels-photo-2475808.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 24500, 95000, 2003, 320, 'Essence', 'Manuelle', 'Espagne', 'ES', 'Barcelona', 'Iberic Motors', 'Professionnel', 3.9, '+34 93 000 0007', 'info@ibericmotors.es', 'https://www.coches.net/911-996-4', 'Coches.net', 58, 7, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":false},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":false},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"critical","title":"Alerte IMS / RMS","description":"996 Phase II — roulement IMS et joint RMS à risque. Remplacement impératif si jamais fait."},{"severity":"critical","title":"Rayures cylindres","description":"Moteur M96 connu pour les rayures de cylindre. Test compression + endoscopie recommandés."},{"severity":"warning","title":"Chauffage pneumatique","description":"Système de chauffage à air souvent défaillant sur les 996. Remplacement par kit électrique."}]'::jsonb, '["Roulement IMS non remplacé — remplacement obligatoire, budget ~2 500 € à déduire du prix.","Kilométrage de 95 000 km élevé pour une 996 — argument principal pour une remise de 3 000 à 4 000 €.","Note vendeur 3.9/5 — fiabilité du vendeur à questionner, demander expertise indépendante."]'::jsonb, '[{"year":2003,"price":65000},{"year":2006,"price":42000},{"year":2009,"price":28000},{"year":2012,"price":20000},{"year":2015,"price":16000},{"year":2018,"price":18000},{"year":2020,"price":21000},{"year":2022,"price":23000},{"year":2024,"price":24000},{"year":2026,"price":24500}]'::jsonb, '{"retentionScore":5,"rarityLabel":"Faible","trend":"stable","trendLabel":"Stabilité garantie","factors":["996 — génération la moins prisée des 911, mais abordable et en hausse","Problèmes moteur M6/M96 bien documentés, freinent la cote","Transmission intégrale 4 sur 996, peu courante, léger premium","Commence à intéresser les jeunes collectionneurs pour son prix d''entrée"]}'::jsonb),
  ('8', '911 Turbo S', '991', 'Turbo S', 'https://images.pexels.com/photos/8631556/pexels-photo-8631556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 165000, 22000, 2018, 580, 'Essence', 'Automatique / PDK', 'Pays-Bas', 'NL', 'Amsterdam', 'Dutch Exotics', 'Professionnel', 4.8, '+31 20 000 0008', 'info@dutchexotics.nl', 'https://www.autoscout24.nl/911-991-turbo-s', 'AutoScout24', 94, 4, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":true}]'::jsonb, '[{"severity":"info","title":"Turbo variable","description":"Géométrie variable des turbos à inspecter. Pas de défaut connu mais entretien crucial."},{"severity":"info","title":"PCCB","description":"Freins carbone céramique à inspecter pour fissures. Remplacement très coûteux si nécessaire."}]'::jsonb, '["Freins PCCB à expertiser — remplacement éventuel à plus de 8 000 €, argument majeur.","Prix 5% au-dessus du marché néerlandais — marge de négociation de 5 000 à 7 000 €.","Pneus arrière large à 40% restant — remplacement à ~400 € à négocier."]'::jsonb, '[{"year":2018,"price":220000},{"year":2020,"price":175000},{"year":2021,"price":168000},{"year":2022,"price":172000},{"year":2023,"price":168000},{"year":2024,"price":166000},{"year":2025,"price":165000},{"year":2026,"price":165000}]'::jsonb, '{"retentionScore":8,"rarityLabel":"Élevée","trend":"stable","trendLabel":"Stabilité garantie","factors":["Turbo S 991.2 — 580 ch, performances supercars au quotidien","Équipement très complet d''origine, peu d''options manquantes","Cote stabilisée après décote initiale, peu de risque de baisse","Demande forte pour les versions Turbo S en Europe du Nord"]}'::jsonb),
  ('9', '911 Carrera RS', '964', 'RS', 'https://images.pexels.com/photos/34780616/pexels-photo-34780616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 195000, 48000, 1992, 260, 'Essence', 'Manuelle', 'Suisse', 'CH', 'Genève', 'Swiss Auto Collection', 'Professionnel', 5, '+41 22 000 0009', 'info@swissautocollection.ch', 'https://www.autoscout24.ch/911-964-rs', 'AutoScout24', 96, 10, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":false},{"key":"chrono","label":"Chrono Plus","present":false},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":false},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"warning","title":"Suspension sport","description":"964 RS à suspension ferme d''origine. Vérifier l''état des amortisseurs Bilstein."},{"severity":"info","title":"Allègement","description":"Véhicule allégé d''origine (absence de banquette arrière, vitres fines). Vérifier l''authenticité."}]'::jsonb, '["Amortisseurs sport d''origine à vérifier — remplacement ~2 500 € si nécessaire.","Authenticité RS à certifier par Porsche Classic — coût ~800 €, à inclure dans la négociation.","Prix au-dessus de la cote suisse pour le kilométrage — marge de 8 000 à 12 000 €."]'::jsonb, '[{"year":1992,"price":80000},{"year":2000,"price":50000},{"year":2005,"price":60000},{"year":2010,"price":85000},{"year":2015,"price":120000},{"year":2018,"price":155000},{"year":2020,"price":175000},{"year":2022,"price":188000},{"year":2024,"price":192000},{"year":2026,"price":195000}]'::jsonb, '{"retentionScore":10,"rarityLabel":"Exceptionnelle","trend":"up","trendLabel":"Plus-value attendue","factors":["964 RS — édition légendaire, l''une des 911 les plus recherchées au monde","Production extrêmement limitée, exemplaires authentiques très rares","Cote en hausse constante depuis 2010, phénomène de collection confirmé","Dernière génération avant l''ABS complet, caractère brut très apprécié"]}'::jsonb),
  ('10', '911 Carrera GTS', '991', 'GTS', 'https://images.pexels.com/photos/9808/pexels-photo-9808.jpg?auto=compress&cs=tinysrgb&h=650&w=940', 98000, 28000, 2015, 430, 'Essence', 'Manuelle', 'Autriche', 'AT', 'Wien', 'Alpine Auto Wien', 'Professionnel', 4.4, '+43 1 000 0010', 'info@alpineauto-wien.at', 'https://www.willhaben.at/911-991-gts', 'Willhaben', 89, 6, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"info","title":"Pack Sport Chrono","description":"Vérifier le bon fonctionnement du bouton Sport Plus sur le volant."},{"severity":"info","title":"Échappement PSE","description":"Vérifier l''état des clapets de l''échappement sport (corrosion possible)."}]'::jsonb, '["Révision des 30 000 km imminente — budget ~600 €, à négocier.","Boîte manuelle sur 991 GTS — rareté recherchée, mais pneus sport à vérifier.","Prix au-dessus de la cote autrichienne de 3 000 € — marge de négociation réaliste."]'::jsonb, '[{"year":2015,"price":135000},{"year":2017,"price":105000},{"year":2019,"price":85000},{"year":2021,"price":88000},{"year":2023,"price":95000},{"year":2025,"price":98000},{"year":2026,"price":98000}]'::jsonb, '{"retentionScore":7.5,"rarityLabel":"Modérée","trend":"stable","trendLabel":"Stabilité garantie","factors":["GTS 991.1 — dernière 911 atmosphérique en version GTS","Boîte manuelle 7 vitesses, de plus en plus rare et recherchée","Cote stabilisée, légère hausse depuis 2022","Position idéale entre Carrera S et GT3 pour l''usage quotidien"]}'::jsonb),
  ('11', '911 Targa 4S', '992', 'Targa 4S', 'https://images.pexels.com/photos/5589320/pexels-photo-5589320.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 155000, 8000, 2023, 450, 'Essence', 'Automatique / PDK', 'Portugal', 'PT', 'Lisboa', 'Iberic Sports Cars', 'Professionnel', 4.3, '+351 21 000 0011', 'info@ibericsportscars.pt', 'https://www.standvirtual.com/911-992-targa-4s', 'Standvirtual', 90, 2, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":true},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"info","title":"Toit Targa","description":"Mécanisme du toit Targa à tester plusieurs fois. Système complexe, entretien coûteux."},{"severity":"info","title":"Garantie","description":"Véhicule sous garantie constructeur. Vérifier le transfert international de la garantie."}]'::jsonb, '["Mécanisme Targa à expertiser — entretien futur potentiellement coûteux, argument de précaution.","Véhicule quasi neuf — peu de marge, négocier entretien offert et extension de garantie.","Toit Targa rare sur le marché d''occasion — prix justifié mais options manquantes à souligner."]'::jsonb, '[{"year":2023,"price":168000},{"year":2024,"price":160000},{"year":2025,"price":156000},{"year":2026,"price":155000}]'::jsonb, '{"retentionScore":6.5,"rarityLabel":"Modérée","trend":"down","trendLabel":"Décote résiduelle","factors":["Targa 992 — mécanisme du toit iconique mais complexe et coûteux à entretenir","Décote normale en cours, véhicule encore récent","Rareté relative sur le marché, mais demande niche","Cote à surveiller, la Targa décote généralement plus qu''un Coupé"]}'::jsonb),
  ('12', '911 Carrera S', '997', 'Phase II', 'https://images.pexels.com/photos/4227198/pexels-photo-4227198.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 52000, 67000, 2010, 385, 'Essence', 'Manuelle', 'Luxembourg', 'LU', 'Luxembourg', 'Particulier', 'Particulier', 3.5, '+352 00 000 0012', 'particulier.luxembourg@example.lu', 'https://www.autoscout24.lu/911-997-2-lux', 'AutoScout24', 78, 8, '[{"key":"x51","label":"X51 Powerkit","present":false},{"key":"pse","label":"Échappement Sport PSE","present":true},{"key":"chrono","label":"Chrono Plus","present":true},{"key":"sportSeats","label":"Sièges Sport","present":true},{"key":"sportChrono","label":"Pack Sport Chrono","present":false},{"key":"carbonBrakes","label":"Freins Carbone PCCB","present":false}]'::jsonb, '[{"severity":"warning","title":"Historique d''entretien","description":"Vendeur particulier — demander l''intégralité du carnet d''entretien et des factures."},{"severity":"warning","title":"Embrayage","description":"67 000 km en boîte manuelle — embrayage potentiellement en fin de vie. Budget ~1 500 €."},{"severity":"info","title":"PCM 3.0","description":"Système PCM à mettre à jour pour compatibilité Bluetooth."}]'::jsonb, '["Vendeur particulier sans garantie — argument principal pour une remise de 2 000 à 3 000 €.","Embrayage à 67 000 km non facturé — remplacement imminent, ~1 500 € à déduire.","Note vendeur 3.5/5 — manquements dans l''historique à exploiter pour la négociation."]'::jsonb, '[{"year":2010,"price":100000},{"year":2012,"price":75000},{"year":2014,"price":58000},{"year":2016,"price":48000},{"year":2018,"price":45000},{"year":2020,"price":47000},{"year":2022,"price":50000},{"year":2024,"price":52000},{"year":2026,"price":52000}]'::jsonb, '{"retentionScore":8,"rarityLabel":"Élevée","trend":"up","trendLabel":"Plus-value attendue","factors":["997 Phase II en boîte manuelle — configuration de plus en plus rare","Cote en hausse, la 997 devient un modèle culte","Dernière 911 à moteur atmosphérique avant la 991 turbo","Demande forte pour les versions manuelles, offre limitée"]}'::jsonb)
on conflict (id) do nothing;
